#include <stdio.h> /* printf */
#include <stdlib.h> 
#include <iostream>
#include <dirent.h>

using namespace std;

int main(int argc, char *argv[])
{
// Calls ls and redirects the output to a txt file
system("ls ./testsequence/ > dirlist.txt");

// Open the .txt file and read the list of files. They should be in the correct order generated by ls. 

return 0;
}